services:
  data-collection:
    build:
      context: .
      dockerfile: backend-data-collection/Dockerfile
    ports:
      - "0.0.0.0:8001:80"
    env_file:
      - backend-data-collection/.env

  map-management:
    build:
      context: .
      dockerfile: backend-map-management/Dockerfile
    ports:
      - "0.0.0.0:8002:80"
    env_file:
      - backend-map-management/.env

  route-management:
    build:
      context: .
      dockerfile: backend-route-management/Dockerfile
    ports:
      - "0.0.0.0:8003:80"
    env_file:
      - backend-route-management/.env

  user-management:
    build:
      context: .
      dockerfile: backend-user-management/Dockerfile
    ports:
      - "0.0.0.0:8004:80"
    env_file:
      - backend-user-management/.env

  navigation-management:
    build:
      context: .
      dockerfile: backend-navigation-management/Dockerfile
    ports:
      - "0.0.0.0:8005:80"
    env_file:
      - backend-navigation-management/.env
