events {}

http {
  server {
    listen 80;

    location = / {
      default_type application/json;
      return 200 '{"gateway":"ok"}';
    }

    location /data-collection/ {
      rewrite ^/data-collection/(.*)$ /$1 break;
      proxy_pass http://data-collection:80;
    }

    location /map/ {
      rewrite ^/map/(.*)$ /$1 break;
      proxy_pass http://map-management:80;
    }

    location /route/ {
      rewrite ^/route/(.*)$ /$1 break;
      proxy_pass http://route-management:80;
    }

    location /user/ {
      rewrite ^/user/(.*)$ /$1 break;
      proxy_pass http://user-management:80;
    }

    location /navigation/ {
      rewrite ^/navigation/(.*)$ /$1 break;
      proxy_pass http://navigation-management:80;
    }
  }
}
