[project]
name = "backend-ai-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MiguelCock", email = "maiguec999@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
torchvision = [
  { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[project.scripts]
dev = "backend_ai_training.main:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
